name: HugoDeployToGitHubPages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Falls dein Hugo-Projekt Git Submodule verwendet

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
